# -*- Makefile -*-

# © 2010 Intel Corporation

# Simics module makefile

MODULE_COMPONENTS := pci_camera_component
SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = pci_camera_component.py module_load.py

include $(MODULE_MAKEFILE)
