#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/daniel/Desktop/SIMICS/simics-6.0.198"
export SIMICS_BASE_PACKAGE
export SIMICS_PYTHON_PACKAGE="/home/daniel/Desktop/SIMICS/simics-6.0.198"
if [ -f "/home/daniel/simics-projects/pci-camera/.package-list" ]; then
    exec "/home/daniel/Desktop/SIMICS/simics-6.0.198/bin/simics-eclipse" --package-list "/home/daniel/simics-projects/pci-camera/.package-list" --project "/home/daniel/simics-projects/pci-camera" "$@"
else
    exec "/home/daniel/Desktop/SIMICS/simics-6.0.198/bin/simics-eclipse" --project "/home/daniel/simics-projects/pci-camera" "$@"
fi
