
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/home/daniel/Desktop/SIMICS/simics-6.0.198
RAW_SIMICS_MODEL_BUILDER=/home/daniel/Desktop/SIMICS/simics-6.0.198
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/home/daniel/Desktop/SIMICS/simics-6.0.198
RAW_PYTHON_PKG=/home/daniel/Desktop/SIMICS/simics-6.0.198

RAW_SIMICS_PACKAGE_LIST=/home/daniel/Desktop/ProyectoEmpotrados/pcicamera/.package-list

INCLUDE_PATHS = /home/daniel/Desktop/SIMICS/simics-6.0.198/src/include
CXX_INCLUDE_PATHS = /home/daniel/Desktop/SIMICS/simics-6.0.198/linux64/api
DML_INCLUDE_PATHS = /home/daniel/Desktop/SIMICS/simics-6.0.198/linux64/bin/dml/api
HOST_TYPE = linux64
